# Use an intermediate "builder" image to further strip down the JDK and JRE
FROM blitznote/debase:17.10 AS builder
ENV JAVA_PKG=server-jre-8u162-linux-x64.tar.gz \
    JDK_DIR_NAME=jdk1.8.0_162
WORKDIR /tmp/
ADD $JAVA_PKG .
RUN cd $JDK_DIR_NAME/ && \
    # Exclude list from anapsix/alpine-java:8_server-jre
    rm -rf jre/plugin \
	       jre/bin/javaws \
		   jre/bin/jjs \
		   jre/bin/orbd \
		   jre/bin/pack200 \
		   jre/bin/policytool \
		   jre/bin/rmid \
		   jre/bin/rmiregistry \
		   jre/bin/servertool \
		   jre/bin/tnameserv \
		   jre/bin/unpack200 \
		   jre/lib/javaws.jar \
		   jre/lib/deploy* \
		   jre/lib/desktop \
		   jre/lib/*javafx* \
		   jre/lib/*jfx* \
		   jre/lib/amd64/libdecora_sse.so \
		   jre/lib/amd64/libprism_*.so \
		   jre/lib/amd64/libfxplugins.so \
		   jre/lib/amd64/libglass.so \
		   jre/lib/amd64/libgstreamer-lite.so \
		   jre/lib/amd64/libjavafx*.so \
		   jre/lib/amd64/libjfx*.so \
		   jre/lib/ext/jfxrt.jar \
		   jre/lib/ext/nashorn.jar \
		   jre/lib/oblique-fonts \
		   jre/lib/plugin.jar \
    # Additional excludes as per http://www.oracle.com/technetwork/java/javase/jre-8-readme-2095710.html
	       jre/lib/ext/* \
           jre/bin/keytool \
           jre/bin/kinit \
           jre/bin/klist \
           jre/bin/ktab \
		   jre/lib/jfr \
		   jre/lib/jfr.jar \
	# Excludes as per https://blogs.oracle.com/jtc/reducing-your-java-se-runtime-environment-footprint-legally
	       jre/lib/charsets.jar \
    # Additional non-official excludes (use at your own risk)
	       man/* \
		   jre/lib/fonts/* \
		   lib/sa-jdi.jar \
		   lib/jconsole.jar

# Copy the stripped down JRE and create the final image
FROM blitznote/debase:17.10
LABEL maintainer="Dhyan Blum <dhyanb@gmail.com>" \
      description="An Oracle Server JRE 8 image based on a minimal version of Debian Stretch."
ENV JDK_DIR_NAME=jdk1.8.0_162 \
    JAVA_HOME=/usr/java/default
COPY --from=builder /tmp/$JDK_DIR_NAME /usr/java/$JDK_DIR_NAME
RUN export JAVA_DIR=/usr/java/$JDK_DIR_NAME && \
    ln -s $JAVA_DIR /usr/java/latest && \
    ln -s $JAVA_DIR /usr/java/default && \
    update-alternatives --install /usr/bin/java java $JAVA_DIR/bin/java 20000 && \
    update-alternatives --install /usr/bin/javac javac $JAVA_DIR/bin/javac 20000 && \
    update-alternatives --install /usr/bin/jar jar $JAVA_DIR/bin/jar 20000